# Generated by Django 5.2.17 on 2026-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedevent',
            name='requires_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='normalizedevent',
            name='review_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='normalizedevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
