# Generated by Django 5.2.17 on 2026-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('normalization', '0002_normalizedevent_requires_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=128, unique=True)),
                ('entity_type', models.CharField(blank=True, choices=[('SHIPMENT', 'Shipment'), ('INVOICE', 'Invoice'), ('UNCLASSIFIED', 'Unclassified')], default='', help_text='Forced entity type, or blank to let the normaliser classify.', max_length=32)),
                ('id_paths', models.JSONField(blank=True, default=list)),
                ('status_paths', models.JSONField(blank=True, default=list)),
                ('time_paths', models.JSONField(blank=True, default=list)),
                ('status_map', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('MANUAL', 'Hand written'), ('DISCOVERED', 'Discovered from samples')], default='MANUAL', max_length=16)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor'],
            },
        ),
        migrations.AddField(
            model_name='normalizedevent',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('approve', 'Approved'), ('reject', 'Rejected')], default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='normalizedevent',
            index=models.Index(condition=models.Q(('requires_review', True), ('reviewed_at__isnull', True)), fields=['created_at'], name='norm_review_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedevent',
            index=models.Index(fields=['confidence_score', 'created_at'], name='norm_confidence_idx'),
        ),
    ]
